Add missing icons to menus
equeim/tremotesf2 pull request #68
Opened 2022-02-04 18:46 UTC by buckmelanoma

This patch adds several missing icons to the following menu items:

mainwindow.cpp:
- invert selection
- set location
- rename
- servers
- server options
- server stats

torrentfilesview.cpp:
- download
- not download
- rename

Sample Screenshots:

Before:
![before](https://user-images.githubusercontent.com/43704682/152585473-668fdb23-c31d-477c-8eee-ac7820cce238.png)

After:
![after](https://user-images.githubusercontent.com/43704682/152585508-e73d9d9a-1796-4534-805f-1427e34fc667.png)

2022-02-04 20:39 UTC, equeim commented
Please add new icons to the list in data/CMakeLists.txt (https://github.com/equeim/tremotesf2/blob/master/data/CMakeLists.txt#L96) so that they will be automatically deployed in Windows builds (only if they exist in breeze icon theme, you can check it by searching [here](https://github.com/KDE/breeze-icons/find/v5.89.0)).

2022-02-05 01:56 UTC, buckmelanoma commented
I added the new icon file names to data/CMakeLists.txt where needed.  Build is clean here on Linux.

I noticed there were some existing duplicate entries in there (ex. "view-refresh.svg"). Is this needed when there are duplicate calls in the source?

2022-02-05 19:49 UTC, equeim commented
No, duplicates are an error (it shouldn't break anything though, it will just make generated regex for finding icons bigger and slower). You can remove them if you want.

Could you also sqash commits into one and rebase is on top of current master (I merged some changes that make GitHub Actions run for Windows faster)?

2022-02-05 19:51 UTC, equeim requested changes

2022-02-05 19:51 UTC, equeim commented on data/CMakeLists.txt
> +	    dialog-cancel.svg
There seems to be an issue with indentation :)

2022-02-12 17:16 UTC, merged

2022-02-12 17:16 UTC, equeim commented
Nice, thank you!